# Generated by Django 5.0.7 on 2024-07-22 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investor_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investor',
        ),
    ]
